### ISSUE TITLE
Handling new synonyms

### ISSUE THREAD

**Issue by damianooldoni** [riparias/riparias-target-list#23]
There are some changes in the GBIF taxonomy backbone which we should take into account. Two of our taxa as published on GBIF are now pointing to two synonyms:
- [Egeria densa](https://www.gbif.org/species/5329260) is now synonym of [Elodea densa](https://www.gbif.org/species/5329263)
- [Heracleum sosnowskyi](https://www.gbif.org/species/3642949) is now synonym of [Heracleum pubescens](https://www.gbif.org/species/3628608)

What does it means? I use the taxon keys related to the taxa as in the GBIF backbone for the early alert. So, we risk to miss some occurrences in the future in case somebody will publish data using the accepted taxon or other synonyms linked to it.

If you trust this synonymy link GBIF did, then I recommend to update the RIPARIAS target species list using the accepted names.

**Comment by timadriaens** [comment]
@damianooldoni in principle no problem to use the accepted name, although I think it will take some time before these new taxonomic insights will be taken into account in the various databases (cf. MAP and obs.be still use Egeria densa and will keep doing this probably, also it is their good right to have their own opinion on whether or not to follow new taxonomic insight of course).

- [Heracleum sosnowskyi](https://www.gbif.org/species/3642949): for the Union List species I think we should stick to the name mentioned in the legislative regime (updated consolidated versions of the Union List, which mention new synonyms, are regularly published, the last one can be found [here](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02016R1141-20220802&from=EN)). Otherwise, people will get confused or not realize it's on the list. In the background, of course, when we do gbif downloads, **all relevant keys should be addressed** so we don't miss any data.
- [Egeria densa](https://www.gbif.org/species/5329260): no problem to use the accepted name (the synonym is already quite old)

I am still in favour of publishing the Union List as a checklist on gbif but we still have no clue as to who should author it. Perhaps, it would be best actually to use a generic author, e.g. "RIPARIAS (2023). xxx". This way, no one claims a list that is not theirs, and at the same time it is clear which project uses it and who transposed the list to the gbif backbone.

**Comment by damianooldoni** [comment]
@timadriaens: thanks.

Some answers to your thoughts:

1. In the document you menion I didn't found any new synonym of H. sosnowskyi. I understand your concern to stick to the EU list as much as possible
2. Egeria densa is not on the list so we can change it. Nice to read you agree on it 👍 1

I agree on the solution of using the keys of the accepted taxa for triggering downloads so we have all the occurrences. Of course we should probably pay attention to mention on the early alert tool About page how it works so that people are not confused about getting data of H. pubescens instead of H. sosnowskyi for example.

**Comment by damianooldoni** [comment]
Notice that there is already an ID sheet available mentioning Egeria densa, see https://www.riparias.be/628/download
Can we update it online? Maybe yes, but not on paper.

So, the most conservative way of proceeding could be to stick with Egeria densa as we probably will do with H. sosnowskyi.

**Comment by damianooldoni** [comment]
Agreed to leave the taxa as they are in the checklist. We will use the nubKey of the accepted in the early alert tool.
